#!/usr/bin/env python
import argparse

"""Parses the raw logs produced by the ./test.sh script in this directory,
   and produces a Gnuplot input data file that can be subsequently fed into
   the `../plot-graph` script to produce a plot of the data"""

def main(inputFile, outputFile):
  # First, read the raw log from the ./test.sh script and parse out
  # times and input parameters
  localHashTableTimes = dict()
  globalHashTableTimes = dict()
  bs = set()
  ps = set()
  with open(inputFile, 'r') as f:
    b, p = None, None
    for line in f:
      if "n=" in line and "b=" in line and "p=" in line:
        [nStr, bStr, pStr] = line.split(", ")
        b = int(bStr.split("=")[1])
        p = float(pStr.split("=")[1])
        bs.add(b)
        ps.add(p)
        if b not in localHashTableTimes: localHashTableTimes[b] = dict()
        if b not in globalHashTableTimes: globalHashTableTimes[b] = dict()
        if p not in localHashTableTimes[b]: localHashTableTimes[b][p] = []
        if p not in globalHashTableTimes[b]: globalHashTableTimes[b][p] = []
      elif "Local" in line:
        time = float(line.split()[1])
        localHashTableTimes[b][p].append(time)
      elif "Global" in line:
        time = float(line.split()[1])
        globalHashTableTimes[b][p].append(time)

  # Normalize all the data.
  """
  maximum = 0.0
  for b in localHashTableTimes:
      for p in localHashTableTimes[b]:
          localHashTableTimes[b][p] = [sum(localHashTableTimes[b][p]) / len(localHashTableTimes[b][p])]
          maximum = max(maximum, localHashTableTimes[b][p][0])
  for b in globalHashTableTimes:
      for p in globalHashTableTimes[b]:
          globalHashTableTimes[b][p] = [sum(globalHashTableTimes[b][p]) / len(globalHashTableTimes[b][p])]
          maximum = max(maximum, globalHashTableTimes[b][p][0])

  for b in localHashTableTimes:
      for p in localHashTableTimes[b]:
          localHashTableTimes[b][p] = [x / float(maximum) for x in localHashTableTimes[b][p]]
  for b in globalHashTableTimes:
      for p in globalHashTableTimes[b]:
          globalHashTableTimes[b][p] = [x / float(maximum) for x in globalHashTableTimes[b][p]]
  """

  # Now, write out parsed data in the format expected by Gnuplot:
  #
  # #	<Col1 Name>	<Col2 Name> ...
  # RowValue ColValue1 ColValue2 ....
  #
  # Here, the output file is prefaced by the 'header', which contains the
  # the title of each line in the plot (separated by tab spaces)
  # Every subsequent line is a list of space-delimited numbers (the first
  # number being the row value, and all subsequent values being the corresponding
  # column value
  ps = list(ps); ps.sort()
  bs = list(bs); bs.sort()
  with open(outputFile, 'w') as f:
    headerStrs = list()
    for p in ps:
      headerStrs.append("p=%.4f (Local)" % p)
      headerStrs.append("p=%.4f (Global)" % p)
    f.write("#\t%s\n" % "\t".join(headerStrs))
    for b in bs:
      f.write("%.2f" % b)
      for p in ps:
        f.write(" %.2f" % (sum(localHashTableTimes[b][p]) / len(localHashTableTimes[b][p])))
        f.write(" %.2f" % (sum(globalHashTableTimes[b][p]) / len(globalHashTableTimes[b][p])))
      f.write("\n")


if __name__ == '__main__':
  parser = argparse.ArgumentParser(
    description=("Produce plot of data dumped in provided data file")
  )
  parser.add_argument('-i', "--inputFile", required=True,
    help="Name of file with raw data produced by test.sh")
  parser.add_argument('-o', "--outputFile", required=True,
    help="Name of file where parsed data needs to be dumped")

  cmdLineArgs = parser.parse_args()
  optDict = vars(cmdLineArgs)

  main(optDict["inputFile"], optDict["outputFile"])
