#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/raw/randlookup

rm -rf $RAW
rm -f $CBO/plots/randlookup_plot.pdf

mkdir -p $RAW

$CBO/randlookup_bench/test.sh > $RAW/raw.out
$CBO/scripts/parse-randlookup-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph -i $RAW/processed.out -o $CBO/randlookup_plot -x "RandAccess Len" -y "Time (in seconds)" -d $CBO/plots -c 0,1,2,3,4,5 -l
