#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/raw/kmeans_bench

#rm -rf $RAW
rm -f $CBO/plots/kmeans_bench_plot.pdf

#mkdir -p $RAW

#$CBO/kmeans_bench/test.sh > $RAW/raw.out
$CBO/scripts/parse-kmeans-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m2 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 0,1
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m4 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 2,3
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m8 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 4,5
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m128 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 6,7
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m256 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 8,9
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m512 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 10,11
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m1024 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 12,13
$CBO/scripts/plot-graph-pairs -i $RAW/processed.out -o $CBO/kmeans_plot_m2048 -x "k (Clusters)" -y "Time (in seconds)" -d $CBO/plots -c 14,15
