#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/raw/matrix_multiplication

rm -rf $RAW
rm -f $CBO/plots/matrix_multiplication_plot.pdf

mkdir -p $RAW

$CBO/matrix_multiplication_bench/test.sh > $RAW/raw.out
$CBO/scripts/parse-matrix-multiplication-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph -i $RAW/processed.out -o matrix_multiplication_plot -x "Dimension of matrix" -y "Time (in seconds)" -d $CBO/plots -c 0,1,2,3,4,5
