#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi


# The root CBO directory
RAW=$CBO/q6_costs_raw

rm -rf $RAW
rm -f $CBO/q6_cost_plot.pdf

mkdir $RAW

python $CBO/pred_query_test.py > $RAW/raw.out
$CBO/scripts/parse-q6-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph -i $RAW/processed.out -o $CBO/q6_cost_plot -x Selectivity -y Cost -d $CBO/plots -c 0,1,2,3,4,5
