#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/costs_raw

rm -rf $RAW
rm -f $CBO/cost_plot.pdf 

mkdir $RAW

python $CBO/pred_query_test.py > $RAW/cost_raw
$CBO/scripts/parse-logs -i $RAW/cost_raw -o $RAW/costData
$CBO/scripts/plot-graph -i $RAW/costData -o $CBO/cost_plot -x Selectivity -y Cost -d $CBO -c 0,1,8,9
