#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/q6_raw

rm -rf $RAW
rm -f $CBO/q6_plot.pdf 

mkdir $RAW

$CBO/q6_bench/test.sh > $RAW/q6_raw
$CBO/scripts/parse-q6-logs -i $RAW/q6_raw -o $RAW/q6Data
$CBO/scripts/plot-graph -i $RAW/q6Data -o $CBO/q6_plot -x Selectivity -y "Time (in seconds)" -d $CBO -c 0,1,2,3,4,5
