#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/nested_loops_raw

rm -rf $RAW
rm -f $CBO/nested_loops_plot.pdf 

mkdir $RAW

$CBO/nested_loops_bench/test.sh > $RAW/nested_loops_raw
$CBO/scripts/parse-nested-loops-logs -i $RAW/nested_loops_raw -o $RAW/nestedLoopsData
$CBO/scripts/plot-graph -i $RAW/nestedLoopsData -o nested_loops_plot -x "Number of elements" -y Time -d $CBO -c 0,1,2,3,4,5
