#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi


# The root CBO directory
RAW=$CBO/raw/q3_costs

rm -rf $RAW
rm -f $CBO/plots/q3_cost_plot.pdf

mkdir -p $RAW

python $CBO/q3_cost.py > $RAW/raw.out
$CBO/scripts/parse-q3-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph -i $RAW/processed.out -o $CBO/q3_cost_plot_p1 -x "Keys" -y "Cost" -d $CBO/plots -c 8,9 -l -m
$CBO/scripts/plot-graph -i $RAW/processed.out -o $CBO/q3_cost_plot_p001 -x "Keys" -y "Cost" -d $CBO/plots -c 0,1 -l -m
