#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi  


# The root CBO directory
RAW=$CBO/nested_loops_raw

rm -rf $RAW
rm -f $CBO/plots/nested_loops_plot.pdf

mkdir $RAW

$CBO/nested_loops_bench/test.sh > $RAW/raw.out
$CBO/scripts/parse-nested-loops-logs -i $RAW/raw.out -o $RAW/processed.out
$CBO/scripts/plot-graph -i $RAW/processed.out -o nested_loops_plot -x "Number of array passes" -y "Time (in seconds)" -d $CBO/plots -c 0,1,2,3,4,5
