#!/bin/bash

if [ -z "$CBO" ]; then
    echo "Set CBO to root of this repo."
    exit 1
fi


# The root CBO directory
RAW=$CBO/nested_loops_costs_raw

rm -rf $RAW
rm -f $CBO/nested_loops_cost_plot.pdf

mkdir $RAW

python $CBO/loop_swap_test.py > $RAW/nested_loops_cost_raw
$CBO/scripts/parse-nested-loops-logs -i $RAW/nested_loops_cost_raw -o $RAW/nestedLoopsCostData
$CBO/scripts/plot-graph -i $RAW/nestedLoopsCostData -o nested_loops_cost_plot -x "Number of array passes" -y Cost -d $CBO -c 0,1,2,3,4,5
